### ISSUE TITLE
为什么采用yolov5-p6.yaml的修改版本训练不起来？（mAP50才0.00095)

### ISSUE THREAD

**Issue by xingguang12** [positive666/yolo_research#89]
## ❔Question
![Snipaste_2023-03-01_10-10-01](https://user-images.githubusercontent.com/57353111/222026674-d504acd5-d446-4a61-9353-5fe7a8902edf.png)
采用yolov5-p6.yaml的修改版本，只是将depth_multiple改成0.33，width_multiple改成0.3，就训练不起来
![Snipaste_2023-03-01_09-57-15](https://user-images.githubusercontent.com/57353111/222026964-f683c852-9806-429b-8d61-543236a4462a.png)
网络架构图
![Snipaste_2023-03-01_10-14-17](https://user-images.githubusercontent.com/57353111/222027424-470ca070-d125-46e2-a0fc-9940c897fdc2.png)

**Comment by positive666** [comment]
超参数用的哪套

**Comment by positive666** [comment]
你基于官方YOLO5修改的结构吗

**Comment by xingguang12** [comment]
> 你基于官方YOLO5修改的结构吗

是的啊，
https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p6.yaml
所进行的改动：把yolov5-p6的depth_multiple改成0.33，width_multiple改成0.3
改动原因：复现所看的论文
论文链接：https://www.mdpi.com/2076-3417/13/3/1746

**Comment by positive666** [comment]
> > 你基于官方YOLO5修改的结构吗
> 
> 是的啊， https://github.com/ultralytics/yolov5/blob/master/models/hub/yolov5-p6.yaml 所进行的改动：把yolov5-p6的depth_multiple改成0.33，width_multiple改成0.3 改动原因：复现所看的论文 论文链接：https://www.mdpi.com/2076-3417/13/3/1746

（不知道你是否排除了一些明显的问题，比如你换了原版模型是正常的精度） 最近分身乏术了  你描述的这个是你把模型压缩了  超参数学习率调整  ，我MARK下 不过要等我把V8整理好了再说
