### ISSUE TITLE
AttributeError: 'V8_Detect' object has no attribute 'na'

### ISSUE THREAD

**Issue by darkredrock** [positive666/yolo_research#92]
## ❔Question
python train.py --cfg models/detect/v8_cfg/yolov8su_ghostv2.yaml --data data/mydata.yaml --device 0 --weights weights/yolov8s.pt
这样跑v8的模型时，报如下错误：AttributeError: 'V8_Detect' object has no attribute 'na'

**Comment by positive666** [comment]
1.你使用的脚本是V5的，目前这个脚本不支持V8，python yolo/v8/detect/train.py 提供了脚本，并且同样可以按照v8仓库自己构建一个训练脚本也是可以的
2.更新下今天的仓库代码，我目前默认的是使用下yolo/v8/detect/train.py，你可以看一下，基本就是先加载yaml然后可以load权重，超参数等调整都在yolo\cfg\下的yaml中，你可以自己设计，给weigths和yaml结构，
