### ISSUE TITLE
v8的训练似乎无法加载预训练权重

### ISSUE THREAD

**Issue by TsaoChao** [positive666/yolo_research#93]
## ❔Question
我对yolov8进行了一些修改，但只要追加模块，官方的训练，就会报keyerror：模块名的错误。于是我尝试使用本仓库的train_v8.py进行训练，但是发现似乎无法加载预训练权重？想请问一下要如何在不依赖官方环境的情况下，要如何加载预训练权重。

**Comment by positive666** [comment]
> ## ❔Question
> 我对yolov8进行了一些修改，但只要追加模块，官方的训练，就会报keyerror：模块名的错误。于是我尝试使用本仓库的train_v8.py进行训练，但是发现似乎无法加载预训练权重？想请问一下要如何在不依赖官方环境的情况下，要如何加载预训练权重。
> 
> ## Additional context
这个问题之前有提到，你对修改后的进行直接读取加载是会报错的，第一次使用想用官方的权重，需要安装官方源码依赖才能打开；不依赖于官方环境的办法是1.你先安装他的依赖训练自己生成自己的模型或者自己遍历需改KEY，这样模型的KEY就被更新了 

你需要修改default.yaml进行自定义权重训练，这个我之前初步测试了下还没更新，这周去弄大模型了 后面更一下 感谢反馈
